A/A/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('exams/', include('exams.urls', namespace='exams')),
]

A/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
	path('register/', views.UserRegisterView.as_view(), name='user_register'),
	path('login/', views.UserLoginView.as_view(), name='user_login'),
	path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
]

A/home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
	path('', views.HomeView.as_view(), name='home'),
]

A/templates/includes/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

A/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-nav">
            <a class="nav-link active" href="{% url 'home:home' %}">Home</a>
            {% if request.user.is_authenticated %}
                <a class="nav-link active" href="{% url 'accounts:user_logout' %}">Logout</a>
            {% else %}
                <a class="nav-link active" href="{% url 'accounts:user_register' %}">Register</a>
                <a class="nav-link active" href="{% url 'accounts:user_login' %}">Login</a>
            {% endif %}
        </div>
    </div>
</nav>